svr_config:
  port: 8010
  name: "messagesvr"
  host: "117.72.16.121"

log:
  level: "debug"
  file_name: "messagesvr.log"
  log_path: "../../log/messagesvr/"
  max_size: 200
  max_age: 30
  max_backups: 7


consul:
    host: "117.72.16.121"
    port: 8500
    tags:
      - "messagesvr"

mysql:
    username: "root"
    password: "123456"
    host: "117.72.16.121"
    port: "8086"
    database: "camps_tiktok"
    max_idle_conn: 10
    max_open_conn: 100
    max_idle_time: 3600


