svr_config:
  port: 8003
  name: "favoritesvr"
  host: "117.72.16.121"
  user_svr_name: "usersvr"
  video_svr_name: "videosvr"

log:
  level: "debug"
  file_name: "favoritesvr.log"
  log_path: "../../log/favoritesvr/"
  max_size: 200
  max_age: 30
  max_backups: 7


consul:
    host: "117.72.16.121"
    port: 8500
    tags:
      - "favoritesvr"

mysql:
    username: "root"
    password: "123456"
    host: "117.72.16.121"
    port: "8086"
    database: "camps_tiktok"
    max_idle_conn: 10
    max_open_conn: 100
    max_idle_time: 3600

