svr_config:
  port: 8004
  name: "videosvr"
  host: "117.72.16.121"


log:
  level: "debug"
  file_name: "videosvr.log"
  log_path: "../../log/videosvr/"
  max_size: 200
  max_age: 30
  max_backups: 7


consul:
    host: "117.72.16.121"
    port: 8500
    tags:
      - "usersvr"

mysql:
    username: "root"
    password: "123456"
    host: "117.72.16.121"
    port: "8086"
    database: "camps_tiktok"
    max_idle_conn: 10
    max_open_conn: 100
    max_idle_time: 3600


minio:
  host: "117.72.16.121"
  port: "9000"
  access_key_id: "WhmqIGLF5cdZLL3ebGd1"
  secret_access_key: "iSWDFxB3ZLCLxRHVPJnqdKt8GqEb7F9rXZxXtDSJ"
  video_buckets: video
  pic_buckets: pic
  video_path: "/root/tiktok/video"
  pic_path: "/root/tiktok/pic"